services:
  api:
    build: .
    container_name: mch-api
    restart: unless-stopped
    ports:
      - "5001:5001"
    env_file: .env
    volumes:
      - uploads_data:/app/uploads
    networks:
      - mch_net

volumes:
  uploads_data:

networks:
  mch_net: